id: P010616
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:39.805539
source_metadata:
  id: bdr:W23913
  title: དཀྱིལ་ཆོག་རྒྱ་མཚོའི་ཐིག་གསལ་བྱེད་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར
  author: ''
  volumes:
    df41bc024d8148a1954207479ff38ed2:
      image_group_id: I3500
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
